"""Grounded-brief generator: builds a machine-checkable claim set for ANY
company from its cache. This is the 'grounded' path of the pipeline made
ticker-generic -- every claim carries its source ref or derivation recipe,
so the verifier can audit it like any other draft.

(The 'ungrounded' draft cannot be generated by code -- it is, by definition,
an LLM writing from memory. That experiment runs interactively in Claude
Code; see CLAUDE.md.)
"""

from __future__ import annotations

import json
from pathlib import Path


def _fmt_musd(x: float) -> str:
    return f"${x/1e9:,.2f}B" if abs(x) >= 1e9 else f"${x/1e6:,.0f}M"


def generate_grounded_brief(cache: dict) -> dict:
    F, meta = cache["facts"], cache["meta"]
    R = meta["resolved"]
    periods = meta["fiscal_periods"]
    fys = sorted(periods)
    cur, prev = fys[-1], fys[-2]
    p_cur, p_prev = periods[cur], periods[prev]
    name = meta.get("ticker", meta.get("entity", "?"))

    def has(logical, period):
        return logical in R and period in F[R[logical]]

    def val(logical, period):
        return F[R[logical]][period]

    claims, i = [], 0

    def fact(text, logical, period):
        nonlocal i
        i += 1
        claims.append({"id": f"a{i:02d}", "text": text, "kind": "fact",
                       "figure": {"value": val(logical, period), "concept": R[logical],
                                  "period_end": period, "unit": "USD"}})

    def derived(text, op, num, den, stated, unit="pct"):
        nonlocal i
        i += 1
        claims.append({"id": f"a{i:02d}", "text": text, "kind": "derived",
                       "derivation": {"op": op,
                                      "numerator": {"concept": R[num[0]], "period_end": num[1]},
                                      "denominator": {"concept": R[den[0]], "period_end": den[1]},
                                      "stated_value": round(stated, 4), "unit": unit}})

    if has("revenue", p_cur):
        rev = val("revenue", p_cur)
        fact(f"{name} generated {_fmt_musd(rev)} of revenue in {cur} (period ended {p_cur}).",
             "revenue", p_cur)
        if has("revenue", p_prev):
            g = rev / val("revenue", p_prev) - 1
            derived(f"Revenue grew {g:+.1%} year-over-year.", "yoy_growth",
                    ("revenue", p_cur), ("revenue", p_prev), g)
    if has("gross_profit", p_cur) and has("revenue", p_cur):
        gm = val("gross_profit", p_cur) / val("revenue", p_cur)
        derived(f"Gross margin was {gm:.1%} in {cur}.", "margin",
                ("gross_profit", p_cur), ("revenue", p_cur), gm)
        if has("gross_profit", p_prev) and has("revenue", p_prev):
            gmp = val("gross_profit", p_prev) / val("revenue", p_prev)
            derived(f"...versus {gmp:.1%} in {prev} ({(gm-gmp)*10000:+.0f}bps).", "margin",
                    ("gross_profit", p_prev), ("revenue", p_prev), gmp)
    if has("operating_income", p_cur) and has("revenue", p_cur):
        om = val("operating_income", p_cur) / val("revenue", p_cur)
        derived(f"Operating margin was {om:.1%} in {cur}.", "margin",
                ("operating_income", p_cur), ("revenue", p_cur), om)
    if has("net_income", p_cur):
        fact(f"Net income was {_fmt_musd(val('net_income', p_cur))} in {cur}.", "net_income", p_cur)
        if has("net_income", p_prev) and val("net_income", p_prev) != 0:
            ng = val("net_income", p_cur) / val("net_income", p_prev) - 1
            derived(f"Net income changed {ng:+.1%} year-over-year.", "yoy_growth",
                    ("net_income", p_cur), ("net_income", p_prev), ng)
    if has("ocf", p_cur):
        fact(f"Operating cash flow was {_fmt_musd(val('ocf', p_cur))} in {cur}.", "ocf", p_cur)
        if has("ocf", p_prev):
            fact(f"...versus {_fmt_musd(val('ocf', p_prev))} in {prev}.", "ocf", p_prev)
    if has("cash", p_cur):
        fact(f"Cash and equivalents ended {cur} at {_fmt_musd(val('cash', p_cur))}.", "cash", p_cur)
    if has("inventory", p_cur):
        fact(f"Inventory ended {cur} at {_fmt_musd(val('inventory', p_cur))}.", "inventory", p_cur)
    if has("rnd", p_cur) and has("revenue", p_cur):
        ri = val("rnd", p_cur) / val("revenue", p_cur)
        derived(f"R&D intensity was {ri:.1%} of revenue in {cur}.", "ratio",
                ("rnd", p_cur), ("revenue", p_cur), ri)
    if has("capex", p_cur) and has("ocf", p_cur):
        fcf = val("ocf", p_cur) - val("capex", p_cur)
        derived(f"Free cash flow (OCF less capex) was {_fmt_musd(fcf)} in {cur}.", "delta",
                ("ocf", p_cur), ("capex", p_cur), fcf, unit="USD")

    for m in meta.get("unresolved_metrics", []):
        i += 1
        claims.append({"id": f"a{i:02d}", "kind": "qualitative",
                       "text": f"[data gap] No usable annual XBRL series found for '{m}' "
                               f"-- claims needing it are out of scope for this company."})

    return {"company": f"{meta.get('entity','?')} ({name})",
            "as_of": meta.get("retrieved"),
            "mode": "grounded -- generated from the EDGAR cache; every figure carries a source ref",
            "claims": claims}


if __name__ == "__main__":
    import sys
    cache = json.loads(Path(sys.argv[1]).read_text())
    out = Path(sys.argv[2])
    out.write_text(json.dumps(generate_grounded_brief(cache), indent=2))
    print(f"wrote {out}")
